README.md
=> Update README.md with AS name

README.md
This is a tiny little PR, just adding all of our names properly here to the README and also linking to the notion site we're working on
Readme looks correct visually on this branch
Negligible, readme still will need a glow up when we have actual instructions on how to clone / use this app but that time is not yet upon us
=> [QA-2] Update README

.gitignore
We should be excluding DS Store files everywhere. This is meaningless but a nit
=> [Git Norms] DS Store

capp-connect/frontend/components/TagCarousel.tsx
[Frontend] F27: Create tag carousel
Created tag carousel to maintain a consistent visual for displaying tags across the app
Looked at it in the app
=> [Frontend] F27: Create tag carousel

capp-connect/backend/ccserver/models.py
Created comments table in models.py
- [x ] My pull request represents one logical piece of work.
- [x ] My commits are related to the pull request and look clean.
- [x ] I have added appropriate tests and documentation to any new code.
=> [Backend] B22: Create comments table

capp-connect/backend/ccserver/serializers.py, capp-connect/backend/ccserver/views.py, capp-connect/backend/connect/urls.py
Contains profile endpoints after local testing:
- Get all profiles (some info)
- Get one profile (all info)
- Update profile (for now, allows anyone to update info about anyone)
- Delete profile (local profile, same issue as update)
Missing same-user verification (for update and delete endpoints). General testing is also pending.
=> Profile Endpoints

.github/workflows/format-and-fail.yml, .pre-commit-config.yaml, capp-connect/frontend/app/(tabs)/_layout.tsx, capp-connect/frontend/app/(tabs)/feed.tsx, capp-connect/frontend/app/(tabs)/index.tsx, capp-connect/frontend/app/(tabs)/resources.tsx, capp-connect/frontend/app/post.tsx, capp-connect/frontend/app/profile.tsx, capp-connect/frontend/app/settings.tsx, capp-connect/frontend/components/EditButton.tsx, capp-connect/frontend/components/FeedCard.tsx, capp-connect/frontend/components/FeedTypeButton.tsx, capp-connect/frontend/components/ProfilePhoto.tsx, capp-connect/frontend/components/SettingsIcon.tsx, capp-connect/frontend/components/TagIcon.tsx, capp-connect/frontend/components/TextField.tsx, capp-connect/frontend/utils/fetchdata.ts
This is just a proposal, I am not the expert on any of this, but this PR resolves all 34 flagged linting issues on the frontend code.
The majority of this is unused imports and other minor things, and in a couple of places I just ignored the rule as I don't think its worth our time to fix
The one place to look at is `post.tsx`, where we have a type and function with the same name. I wasn't sure where these might be used so didn't want to rename.
I want Greg to validate that the app still works as expected from this branch if that's feasible as an ask.
Linting passes now
This will make things easier for others who otherwise will be confused about frontend linting issues. going forwards we can all ensure we pass lint before we merge
=> [QA-2] Proposed TS linting changes

.gitignore, capp-connect/frontend/eslint.config.mjs
[QA]: Updated the eslint.config.mjs file to ignore the app-example when linting
I have the app-example folder on my computer for reference, and although it is never uploaded to git, the precommit linting kept flagging it. I added it to be ignored by the linter and added a more descriptive comment in the .gitignore.
Nothing
Create an app-example/ folder in frontend/ and it should ignore it
Greg's hatred of errors when linting
=> [QA] quality of life improvement: Updated the eslint.config.mjs file to ignore the app-example when linting

capp-connect/backend/ccserver/models.py
- [x ] My pull request represents one logical piece of work.
- [x ] My commits are related to the pull request and look clean.
- [x ] I have added appropriate tests and documentation to any new code.
- [x ] I have updated any relevant README files.
=> [b13 update] models.py resources tags removed, slack dm url added

docs/endpoints/general.md
This pull request contains a list of endpoints to be reviewed by the Chief Architect. Based on the discussion, we will have the final endpoints. After that, the API endpoints documentation will be updated with additional information.
=> redefinition of endpoints for discussion

capp-connect/backend/ccserver/serializers.py, capp-connect/backend/ccserver/views.py, capp-connect/backend/connect/urls.py
Creation and implementation of two endpoints that get lists to facilitate search autocomplete:
- Tags
- Usernames
Currently, we don't have names in the model, but it can be changed to that.
=> [Backend] Endpoints for search autocomplete

capp-connect/backend/connect/urls.py
=> BUG: double listed

capp-connect/backend/authentication/get_replies.py, capp-connect/backend/connect/urls.py
further handling of merge conflicts
=> BUG: two messed up things

capp-connect/backend/ccserver/views.py, capp-connect/backend/connect/settings.py, capp-connect/backend/connect/urls.py
This PR has been in my nightmares and dreams... and somehow was 15 lines of code between me and Paula. We now are able to monitor user sessions through a new simple endpoint that lets us verify who users are.
Auth'd through the server, I was able to edit my own profile, but not Amber's profile. Before we put this in, I was able to edit both. This is a huge win.
We're ready to connect with frontend here, and the edit profile button should work.
=> [D + B] Managing User Sessions

capp-connect/backend/ccserver/tests.py, capp-connect/backend/ccserver/views.py
Tests to check the correct functionality of (most) endpoints. Missing:
- Resources post/delete/update: These endpoints are for internal use only and do not affect the frontend
- Slack Sync: These endpoints haven't been used yet and require connection to the Slack API
Activate for use on pre-commit
=> [Backend] Tests for endpoints

capp-connect/backend/ccserver/views.py, capp-connect/backend/connect/settings.py, capp-connect/backend/connect/urls.py
This pull request includes three additional API endpoints to facilitate the posts sync with Slack channels:
- POST: Creates a new post based on a message that comes from Slack
- PUT: Checks for posts with X time stamp and Y post type, and updates if values are the same 
- DELETE: Checks for posts with X time stamp and Y post type, and deletes if values are the same 
To use it, you will need to define and import these global variables:
API_SLACK_SYNC_URL="http://base-url/**slack-sync/**"
API_AUTH_TOKEN="already shared"
=> [Backend]: Slack Sync Endpoints

capp-connect/backend/connect/settings.py
Greg and I noticed the endpoints were given a token auth error, which was new. This was resolved by moving this line to the correct place. Running from this branch the endpoints work again.
=> BUG: this was in the wrong place

capp-connect/backend/ccserver/tests.py, capp-connect/backend/ccserver/views.py
-->
added resource search test; fixed bug in resource search
- [x ] My pull request represents one logical piece of work.
- [x ] My commits are related to the pull request and look clean.
- [x ] I have added appropriate tests and documentation to any new code.
- [x ] I have updated any relevant README files.
=> added resource search test; fixed bug in resource search

capp-connect/backend/ccserver/serializers.py
Added  client_msg_id and slack_user_id to post serializer
=> added client_msg_id and slack_user_id to serializers

Makefile, capp-connect/backend/ccserver/serializers.py, capp-connect/backend/ccserver/tests.py, capp-connect/backend/ccserver/views.py
Adds tests for slack posts handling and includes them on Makefile. This last part can be taken out if the merge time impact is to high.
=> [Backend] Additional tests

docs/frontend/README.md
=> Updates frontend README.md
